package com.google.calendar.csv.reader;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * This is the interface for CSV file reader.
 *
 * @author DAMCO
 */
public interface CSVReader {

    /**
     * Return Map of input parameter taken from CSV file
     *
     * @param request
     *            HttpServletRequest object with INPUT CSV file.
     * @param response
     *            HttpServletResponse object that will contain Exception message
     *            if occurred
     * @return Map of input parameter generated by reading CSV file.
     */
    public Map<String, String> readCSV(final HttpServletRequest request, final HttpServletResponse response);

}
